----
kind: pipeline
name: Build
type: docker

steps:
  - name: "Quality Control"
    image: cortezaproject/corteza-webapp-builder
    commands:
    - make dep # test


  - name: "Build release (tag)"
    image: cortezaproject/corteza-webapp-builder
    environment:
      RELEASE_SFTP_KEY: { from_secret: RELEASE_SFTP_KEY }
      RELEASE_SFTP_URI: { from_secret: RELEASE_SFTP_URI }
    commands:
    - make build release upload BUILD_VERSION=${DRONE_TAG}
    when:
      event: [ tag ]
      ref:
      - refs/tags/20??.3.*
      - refs/tags/20??.6.*
      - refs/tags/20??.9.*
      - refs/tags/20??.12.*
